openapi: 3.0.3
info:
  title: Avengers Inventory Management API
  description: API for managing inventories in Avengers Corp
  version: 1.0.0
servers:
  - url: 'https://api.avengers.com'
    description: Production server
  - url: 'http://localhost:8080'
    description: Development server
paths:
  /inventories:
    get:
      summary: Get all inventories
      operationId: getInventories
      responses:
        '200':
          description: A list of inventories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Inventory'
    post:
      summary: Create a new inventory
      operationId: createInventory
      requestBody:
        description: Inventory to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Inventory'
      responses:
        '201':
          description: Inventory created successfully
  /inventories/{id}:
    get:
      summary: Get an inventory by ID
      operationId: getInventory
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the inventory
          schema:
            type: integer
      responses:
        '200':
          description: Inventory details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
        '404':
          description: Inventory not found
    put:
      summary: Update an inventory by ID
      operationId: updateInventory
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the inventory
          schema:
            type: integer
      requestBody:
        description: Inventory to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Inventory'
      responses:
        '200':
          description: Inventory updated successfully
    delete:
      summary: Delete an inventory by ID
      operationId: deleteInventory
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the inventory
          schema:
            type: integer
      responses:
        '204':
          description: Inventory deleted successfully
components:
  schemas:
    Inventory:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Iron Man Suit"
        code:
          type: string
          example: "IM001"
        stock:
          type: integer
          example: 10
        description:
          type: string
          example: "Advanced suit for Tony Stark"
        status:
          type: string
          enum:
            - active
            - broken
          example: "active"
